// ─── 200 loại thuốc phổ biến tại Việt Nam (MVP Mock Data) ────────
// Used by AutocompleteInput for medicine name suggestions.
// Sorted by category for maintenance, searched case-insensitively at runtime.

export const COMMON_MEDICINES: string[] = [
    // ═══ 1. GIẢM ĐAU / HẠ SỐT / CẢM CÚM (25) ═══════════════════
    'Paracetamol 500mg',
    'Paracetamol 325mg',
    'Paracetamol 250mg (trẻ em)',
    'Panadol Extra',
    'Panadol Cảm Cúm',
    'Hapacol 650mg',
    'Hapacol 250mg',
    'Efferalgan 500mg',
    'Efferalgan 150mg (trẻ em)',
    'Ibuprofen 400mg',
    'Ibuprofen 200mg',
    'Aspirin 81mg',
    'Aspirin 500mg',
    'Diclofenac 50mg',
    'Diclofenac 75mg',
    'Meloxicam 7.5mg',
    'Meloxicam 15mg',
    'Celecoxib 200mg',
    'Tiffy',
    'Tiffy Dey',
    'Decolgen',
    'Decolgen Forte',
    'Coldacmin Flu',
    'Tydol Flu',
    'Rhumenol 500mg',

    // ═══ 2. KHÁNG SINH (25) ═══════════════════════════════════════
    'Amoxicillin 500mg',
    'Amoxicillin 250mg',
    'Augmentin 625mg',
    'Augmentin 1g',
    'Augmentin 250mg (trẻ em)',
    'Cephalexin 500mg',
    'Cephalexin 250mg',
    'Cefuroxime 500mg',
    'Cefuroxime 250mg',
    'Cefixime 200mg',
    'Cefixime 100mg',
    'Azithromycin 500mg',
    'Azithromycin 250mg',
    'Ciprofloxacin 500mg',
    'Levofloxacin 500mg',
    'Levofloxacin 750mg',
    'Metronidazole 250mg',
    'Metronidazole 500mg',
    'Clindamycin 300mg',
    'Doxycycline 100mg',
    'Erythromycin 500mg',
    'Clarithromycin 500mg',
    'Tinidazole 500mg',
    'Cefpodoxime 200mg',
    'Trimethoprim/Sulfamethoxazole',

    // ═══ 3. KHÁNG VIÊM (10) ══════════════════════════════════════
    'Prednisolone 5mg',
    'Prednisone 5mg',
    'Methylprednisolone 4mg',
    'Methylprednisolone 16mg (Medrol)',
    'Dexamethasone 0.5mg',
    'Alpha Choay',
    'Alphachymotrypsin',
    'Serratiopeptidase',
    'Lysozyme',
    'Danzen 5mg',

    // ═══ 4. TIÊU HÓA / DẠ DÀY (25) ═════════════════════════════
    'Omeprazole 20mg',
    'Omeprazole 40mg',
    'Esomeprazole 20mg',
    'Esomeprazole 40mg (Nexium)',
    'Pantoprazole 40mg',
    'Lansoprazole 30mg',
    'Rabeprazole 20mg',
    'Phosphalugel (thuốc dạ dày chữ P)',
    'Yumangel (thuốc dạ dày chữ Y)',
    'Gaviscon',
    'Gaviscon Advance',
    'Domperidone 10mg (Motilium)',
    'Motilium-M',
    'Oresol',
    'Smecta',
    'Berberin',
    'Loperamide 2mg',
    'Enterogermina',
    'Men tiêu hóa Bioflora',
    'Lactomin Plus',
    'Sorbitol',
    'Duphalac',
    'Bisacodyl 5mg',
    'Maalox',
    'Sucralfate 1g',

    // ═══ 5. HÔ HẤP / HO / VIÊM HỌNG (20) ═══════════════════════
    'Acetylcysteine 200mg',
    'Acetylcysteine 600mg',
    'Ambroxol 30mg',
    'Bromhexine 8mg',
    'Dextromethorphan 15mg',
    'Terpin Codein',
    'Bảo Thanh (sirô ho)',
    'Prospan (sirô thảo dược)',
    'Thuốc ho Nam Hà',
    'Eugica (viên ngậm)',
    'Strepsils',
    'Strepsils Plus',
    'Dorithricin',
    'Salbutamol 2mg',
    'Salbutamol 4mg',
    'Theophylline 200mg',
    'Montelukast 10mg',
    'Fluticasone xịt mũi',
    'Nasonex',
    'Otrivin (xịt mũi)',

    // ═══ 6. DỊ ỨNG / KHÁNG HISTAMIN (10) ════════════════════════
    'Loratadine 10mg',
    'Cetirizine 10mg',
    'Fexofenadine 60mg',
    'Fexofenadine 180mg (Telfast)',
    'Chlorpheniramine 4mg',
    'Desloratadine 5mg',
    'Levocetirizine 5mg',
    'Bilastine 20mg',
    'Ketotifen 1mg',
    'Allegra 120mg',

    // ═══ 7. TIM MẠCH / HUYẾT ÁP (20) ════════════════════════════
    'Amlodipine 5mg',
    'Amlodipine 10mg',
    'Losartan 50mg',
    'Losartan 100mg',
    'Valsartan 80mg',
    'Valsartan 160mg',
    'Telmisartan 40mg',
    'Telmisartan 80mg',
    'Bisoprolol 5mg',
    'Bisoprolol 2.5mg',
    'Atenolol 50mg',
    'Atorvastatin 10mg',
    'Atorvastatin 20mg',
    'Rosuvastatin 10mg',
    'Rosuvastatin 20mg',
    'Simvastatin 20mg',
    'Clopidogrel 75mg',
    'Trimetazidine 35mg',
    'Nitroglycerin 2.6mg',
    'Digoxin 0.25mg',

    // ═══ 8. TIỂU ĐƯỜNG (10) ═════════════════════════════════════
    'Metformin 500mg',
    'Metformin 850mg',
    'Metformin 1000mg',
    'Gliclazide 30mg',
    'Gliclazide 60mg (Diamicron)',
    'Glimepiride 2mg',
    'Glimepiride 4mg',
    'Sitagliptin 100mg (Januvia)',
    'Empagliflozin 10mg (Jardiance)',
    'Dapagliflozin 10mg (Forxiga)',

    // ═══ 9. THẦN KINH / GIẤC NGỦ / TÂM THẦN (10) ═══════════════
    'Gabapentin 300mg',
    'Pregabalin 75mg',
    'Amitriptyline 25mg',
    'Sertraline 50mg',
    'Rotundin (Stylnox VN)',
    'Melatonin 3mg',
    'Phenobarbital 100mg',
    'Carbamazepine 200mg',
    'Valproic acid 500mg',
    'Piracetam 800mg',

    // ═══ 10. VITAMIN & THỰC PHẨM CHỨC NĂNG (25) ═════════════════
    'Vitamin C 500mg',
    'Vitamin C 1000mg',
    'Vitamin C + Kẽm (DHG)',
    'Vitamin D3 1000IU',
    'Vitamin D3 5000IU',
    'Vitamin E 400IU (Enat 400)',
    'Vitamin B1 B6 B12',
    'Vitamin B Complex',
    'Vitamin A+D (Aquadetrim)',
    'Omega 3 Fish Oil',
    'Omega 3 6 9',
    'Dầu cá Healthy Care',
    'Calcium + D3',
    'Canxi Corbiere',
    'Canxi Nano',
    'Magne B6',
    'Magne B6 Forte',
    'Sắt Ferrovit',
    'Sắt Fumarate 200mg',
    'Kẽm Zinc Gluconate',
    'Kẽm DHG',
    'Ginkgo Biloba 120mg',
    'Hoạt huyết dưỡng não',
    'Glucosamine 1500mg',
    'Boganic (bổ gan)',

    // ═══ 11. GAN / THẬN / TIẾT NIỆU (10) ════════════════════════
    'Boganic Extra',
    'Silymarin 140mg (Bổ gan)',
    'Ursodeoxycholic acid 250mg',
    'Forlax 10g',
    'Rowatinex (sỏi thận)',
    'Cranberry Extract',
    'Tamsulosin 0.4mg',
    'Finasteride 5mg',
    'Flavoxate 200mg',
    'Spironolactone 25mg',

    // ═══ 12. THUỐC DÙNG NGOÀI / DA LIỄU (10) ═══════════════════
    'Salonpas (miếng dán)',
    'V.Rohto (nhỏ mắt)',
    'Osla (nhỏ mắt)',
    'Natri Clorid 0.9% (nhỏ mũi)',
    'Ketoconazole cream',
    'Gentrisone cream',
    'Dibetalic cream',
    'Clotrimazole cream',
    'Betadine (sát trùng)',
    'Urgo (băng cá nhân)',

    // ═══ 13. SẢN PHỤ KHOA / TRÁNH THAI (5) ════════════════════
    'Postinor (tránh thai khẩn cấp)',
    'Marvelon',
    'Diane 35',
    'Duphaston 10mg',
    'Acid Folic 5mg',
];
